import { DailyNote, Project, Task } from "../types";

export const demoProjects: Project[] = [
  {
    id: "health-reset",
    fileName: "health-reset.md",
    title: "Перезагрузка здоровья",
    status: "active",
    priority: "high",
    area: "health",
    deadline: null,
    progress: 35,
    description: "Базовый трекер привычек + питание",
  },
  {
    id: "career-platform",
    fileName: "career-platform.md",
    title: "Новая платформа портфолио",
    status: "active",
    priority: "medium",
    area: "career",
    deadline: "2024-09-01",
    progress: 50,
    description: "Сайт с кейсами и блогом",
  },
  {
    id: "language-sprint",
    fileName: "language-sprint.md",
    title: "Английский B2",
    status: "waiting",
    priority: "medium",
    area: "learning",
    deadline: null,
    progress: 20,
    description: "Фокус на speaking + listening",
  },
];

const today = new Date().toISOString().slice(0, 10);

export const demoTasks: Task[] = [
  {
    id: "inbox-1",
    title: "Записаться к физиотерапевту",
    description: "После тренировки болит колено",
    projectId: "health-reset",
    area: "health",
    context: "phone",
    estimatedMinutes: 5,
    timeBucket: "micro",
    status: "inbox",
    flags: { quick: true },
    createdAt: today,
    dueDate: null,
    plannedDate: null,
    completedAt: null,
    dailyPriority: false,
    priority: "medium",
  },
  {
    id: "clarified-1",
    title: "Сделать бриф для дизайнера",
    description: "Структура лендинга",
    projectId: "career-platform",
    area: "career",
    context: "desktop",
    estimatedMinutes: 45,
    timeBucket: "medium",
    status: "clarified",
    flags: { frog: true },
    createdAt: today,
    dueDate: "2024-08-30",
    plannedDate: null,
    completedAt: null,
    dailyPriority: false,
    priority: "high",
  },
  {
    id: "next-1",
    title: "Подобрать 3 референса",
    projectId: "career-platform",
    area: "career",
    context: "desktop",
    estimatedMinutes: 20,
    timeBucket: "short",
    status: "next",
    flags: { batchable: true },
    createdAt: today,
    dueDate: null,
    plannedDate: null,
    completedAt: null,
    dailyPriority: false,
    priority: "medium",
  },
  {
    id: "today-1",
    title: "Запись 15 минут speaking",
    projectId: "language-sprint",
    area: "learning",
    context: "phone",
    estimatedMinutes: 15,
    timeBucket: "short",
    status: "planned_today",
    flags: { quick: false },
    createdAt: today,
    dueDate: null,
    plannedDate: today,
    completedAt: null,
    dailyPriority: true,
    priority: "medium",
  },
  {
    id: "waiting-1",
    title: "Ответ от редактора",
    projectId: "career-platform",
    area: "career",
    context: "desk",
    estimatedMinutes: 5,
    timeBucket: "micro",
    status: "waiting",
    flags: { waiting: true },
    createdAt: today,
    dueDate: null,
    plannedDate: null,
    completedAt: null,
    dailyPriority: false,
    priority: "medium",
  },
  {
    id: "done-1",
    title: "Закрыть кольцо активности",
    projectId: "health-reset",
    area: "health",
    context: "outdoor",
    estimatedMinutes: 30,
    timeBucket: "short",
    status: "done",
    flags: {},
    createdAt: today,
    dueDate: null,
    plannedDate: today,
    completedAt: today,
    dailyPriority: false,
    priority: "medium",
  },
];

export const demoDaily: DailyNote[] = [
  {
    date: today,
    fileName: `${today}.md`,
    habits: [
      { id: "h1", title: "Вода 500 мл", block: "Утро", done: false },
      { id: "h2", title: "Растяжка 5 минут", block: "Утро", done: true },
      { id: "h3", title: "План на день", block: "Утро", done: true },
    ],
  },
];
